version: '3'
services:

  chrome:
    image: cypress-docker-image-e2e-tests
    command: "cy:runChromeProd"
    volumes:
      - ./cypress:/cypress
      - ./package.json:/package.json

  firefox:
    image: cypress-docker-image-e2e-tests
    command: "cy:runFirefoxProd"
    volumes:
      - ./cypress:/cypress
      - ./package.json:/package.json
